'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/hooks/use-auth';
import { canManageMembers } from '@/lib/permissions';
import { Role, RoleLabel } from '@/types';

type Department = { id: string; name: string; shortName: string };
type Registration = { id: string; name: string; studentId: string; email: string; status: string; emailVerifiedAt?: string; requestedDepartment?: Department; approvedDepartment?: Department; approvedRole?: Role; reviewNote?: string };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, ...init }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message ?? '请求失败。'); return body.data; }

export default function RegistrationsPage() {
  const { user } = useAuth(); const canManage = canManageMembers(user);
  const [rows, setRows] = useState<Registration[]>([]); const [departments, setDepartments] = useState<Department[]>([]); const [message, setMessage] = useState(''); const [selected, setSelected] = useState<Registration | null>(null); const [departmentId, setDepartmentId] = useState(''); const [role, setRole] = useState<Role>(Role.MEMBER); const [note, setNote] = useState('');
  async function load() { const [registrations, departmentRows] = await Promise.all([api<Registration[]>('/api/admin/registrations'), api<Department[]>('/api/public/departments')]); setRows(registrations); setDepartments(departmentRows); }
  useEffect(() => { if (!canManage) return; let active = true; Promise.resolve().then(load).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : '无法读取申请。'); }); return () => { active = false; }; }, [canManage]);
  function open(row: Registration) { setSelected(row); setDepartmentId(row.approvedDepartment?.id ?? row.requestedDepartment?.id ?? ''); setRole(row.approvedRole ?? Role.MEMBER); setNote(row.reviewNote ?? ''); }
  async function review(action: 'approve' | 'reject' | 'resend-activation', id = selected?.id) { if (!id) return; try { const body = action === 'approve' ? { departmentId, role, reviewNote: note || null } : action === 'reject' ? { reviewNote: note || null } : undefined; const result = await api<{ mailSent?: boolean }>(`/api/admin/registrations/${id}/${action}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined }); setMessage(result.mailSent === false ? '操作已保存，但邮件发送失败；可稍后重新发送。' : '操作成功。'); setSelected(null); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '操作失败。'); } }
  if (!canManage) return <p className="p-10 text-sm text-muted-foreground">无权访问。</p>;
  return <div className="mx-auto max-w-5xl p-6 lg:p-10"><h1 className="text-2xl font-semibold">注册申请</h1><p className="mt-1 text-sm text-muted-foreground">审核已完成学校邮箱验证的申请；批准不会立即创建正式账户。</p>{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}<div className="mt-6 overflow-hidden rounded-xl border bg-white">{rows.map((row) => <div key={row.id} className="flex flex-wrap items-center gap-3 border-b p-4 last:border-0"><div className="min-w-[180px] flex-1"><p className="font-medium">{row.name} <span className="text-xs text-muted-foreground">{row.status}</span></p><p className="text-xs text-muted-foreground">{row.studentId} · {row.email} · {row.requestedDepartment?.name ?? '未选部门'}</p></div><button onClick={() => open(row)} className="rounded-lg border px-3 py-2 text-sm">审核</button>{row.status === 'APPROVED' && <button onClick={() => review('resend-activation', row.id)} className="rounded-lg border px-3 py-2 text-sm">重发激活邮件</button>}</div>)}{rows.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">暂无注册申请。</p>}</div>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><section className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold">审核：{selected.name}</h2><p className="mt-2 text-sm text-muted-foreground">{selected.studentId} · {selected.email} · 邮箱{selected.emailVerifiedAt ? '已验证' : '未验证'}</p><label className="mt-4 block text-sm">最终部门<select value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} className="mt-1 h-10 w-full rounded border px-2">{departments.map((dept) => <option key={dept.id} value={dept.id}>{dept.name}</option>)}</select></label><label className="mt-3 block text-sm">最终身份<select value={role} onChange={(e) => setRole(e.target.value as Role)} className="mt-1 h-10 w-full rounded border px-2">{Object.values(Role).filter((value) => value !== Role.SUPER_ADMIN).map((value) => <option key={value} value={value}>{RoleLabel[value]}</option>)}</select></label><label className="mt-3 block text-sm">审核备注（可能发送给申请人）<textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded border p-2" /></label><div className="mt-5 flex justify-end gap-2"><button onClick={() => setSelected(null)} className="rounded border px-3 py-2 text-sm">取消</button><button onClick={() => review('reject')} className="rounded border px-3 py-2 text-sm text-destructive">拒绝</button><button disabled={!departmentId || selected.status !== 'PENDING'} onClick={() => review('approve')} className="rounded bg-foreground px-3 py-2 text-sm text-background disabled:opacity-50">批准</button></div></section></div>}</div>;
}
