import { apiError, apiSuccess } from '@/lib/api/response';
import { AuthenticationError, requireUser } from '@/lib/auth';
import { deleteFolder, updateFolder } from '@/lib/server/folders';
import { z } from 'zod';

export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
function folderError(error: unknown) { const code = error instanceof Error ? error.message : ''; if (['FOLDER_FORBIDDEN', 'FOLDER_SCOPE_MISMATCH'].includes(code)) return apiError('FORBIDDEN', '无权管理该目录。', 403); if (['FOLDER_NAME_INVALID', 'FOLDER_NOT_FOUND'].includes(code)) return apiError('VALIDATION_ERROR', '目录参数不合法。', 400); if (code.includes('Unique constraint')) return apiError('FOLDER_EXISTS', '同一目录下已存在同名文件夹。', 409); return apiError('REQUEST_FAILED', '目录操作失败。', 500); }
const schema = z.object({ name: z.string().optional(), parentId: z.string().uuid().nullable().optional(), departmentId: z.string().uuid().nullable().optional() }).refine((data) => Object.keys(data).length > 0, '至少提供一个修改字段');
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); const data = schema.safeParse(await request.json().catch(() => null)); if (!data.success) return apiError('VALIDATION_ERROR', '目录数据不合法。', 400); return apiSuccess(await updateFolder(user, (await context.params).id, data.data)); } catch (error) { if (error instanceof AuthenticationError) return apiError('UNAUTHORIZED', error.message, 401); if (error instanceof Error && error.message === 'FOLDER_CYCLE') return apiError('FOLDER_CYCLE', '不能移动到自身或子目录中。', 400); return folderError(error); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { try { const user = await requireUser(); await deleteFolder(user, (await context.params).id); return apiSuccess({ deleted: true }); } catch (error) { if (error instanceof AuthenticationError) return apiError('UNAUTHORIZED', error.message, 401); if (error instanceof Error && error.message === 'FOLDER_NOT_EMPTY') return apiError('FOLDER_NOT_EMPTY', '非空目录不能删除。', 409); return folderError(error); } }
