'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Department = { id: string; name: string; shortName: string };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, ...init }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message ?? '请求失败，请稍后重试。'); return body.data; }
export default function RegisterPage() {
  const [name, setName] = useState(''); const [studentId, setStudentId] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [departments, setDepartments] = useState<Department[]>([]); const [applicationId, setApplicationId] = useState(''); const [code, setCode] = useState(''); const [status, setStatus] = useState<'FORM' | 'EMAIL_PENDING' | 'PENDING'>('FORM'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { request<Department[]>('/api/public/departments').then(setDepartments).catch(() => setMessage('无法加载部门列表，请稍后重试。')); }, []);
  const email = useMemo(() => { const id = studentId.trim().toLowerCase(); const domain = process.env.NEXT_PUBLIC_SCHOOL_EMAIL_DOMAIN; return /^[a-z0-9_-]+$/.test(id) && domain ? `${id}@${domain.toLowerCase()}` : ''; }, [studentId]);
  async function start(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const data = await request<{ applicationId: string }>('/api/auth/register/start', { method: 'POST', body: JSON.stringify({ name, studentId, requestedDepartmentId: departmentId || null }) }); setApplicationId(data.applicationId); setStatus('EMAIL_PENDING'); setMessage('验证码已发送，请查收学校邮箱。'); } catch (error) { setMessage(error instanceof Error ? error.message : '申请失败。'); } finally { setBusy(false); } }
  async function verify(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { await request('/api/auth/register/verify-email', { method: 'POST', body: JSON.stringify({ applicationId, code }) }); setStatus('PENDING'); setMessage('学校邮箱已验证，申请已提交，等待管理员审核。'); } catch (error) { setMessage(error instanceof Error ? error.message : '验证码错误或已失效。'); } finally { setBusy(false); } }
  async function resend() { setBusy(true); setMessage(''); try { await request('/api/auth/register/resend-code', { method: 'POST', body: JSON.stringify({ applicationId }) }); setMessage('验证码已重新发送。'); } catch (error) { setMessage(error instanceof Error ? error.message : '暂时无法重发。'); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#FAFAF8] flex items-center justify-center p-5"><section className="w-full max-w-lg rounded-2xl border border-border bg-white p-6 sm:p-9 shadow-sm"><h1 className="text-2xl font-semibold">申请加入工作台</h1><p className="mt-2 text-sm text-muted-foreground">使用南京师范大学学校邮箱完成验证，管理员审核通过后才会开通账号。</p>{status === 'FORM' && <form onSubmit={start} className="mt-7 space-y-4"><label className="block text-sm font-medium">姓名<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><label className="block text-sm font-medium">学号<input required value={studentId} onChange={(e) => setStudentId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><p className="rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">验证码将发送至：{email || '请输入合法学号'}</p><label className="block text-sm font-medium">申请部门<select required value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3"><option value="">请选择部门</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><button disabled={busy || !email} className="h-11 w-full rounded-lg bg-foreground text-background disabled:opacity-50">{busy ? '发送中…' : '发送验证码'}</button></form>}{status === 'EMAIL_PENDING' && <form onSubmit={verify} className="mt-7 space-y-4"><p className="text-sm">验证码已发送至 <strong>{email}</strong></p><label className="block text-sm font-medium">6 位验证码<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} className="mt-2 h-11 w-full rounded-lg border px-3 tracking-[0.4em]" /></label><button disabled={busy || code.length !== 6} className="h-11 w-full rounded-lg bg-foreground text-background disabled:opacity-50">{busy ? '验证中…' : '验证邮箱'}</button><button type="button" disabled={busy} onClick={resend} className="w-full text-sm text-muted-foreground underline">重新发送验证码</button></form>}{status === 'PENDING' && <div className="mt-7 rounded-lg bg-muted p-4 text-sm leading-6">申请已提交。学校邮箱已验证，请等待管理员审核；审核通过后会向该邮箱发送账号激活链接。</div>}{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}<p className="mt-7 text-center text-sm text-muted-foreground">已有账号？<Link href="/login" className="underline">登录</Link></p></section></main>;
}
