'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Department = { id: string; name: string; shortName: string };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, ...init }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message ?? '请求失败，请稍后重试。'); return body.data; }
export default function RegisterPage() {
  const [name, setName] = useState(''); const [studentId, setStudentId] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [departments, setDepartments] = useState<Department[]>([]); const [status, setStatus] = useState<'FORM' | 'PENDING'>('FORM'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { request<Department[]>('/api/public/departments').then(setDepartments).catch(() => setMessage('无法加载部门列表，请稍后重试。')); }, []);
  const email = useMemo(() => { const id = studentId.trim().toLowerCase(); const domain = process.env.NEXT_PUBLIC_SCHOOL_EMAIL_DOMAIN; return /^[a-z0-9_-]+$/.test(id) && domain ? `${id}@${domain.toLowerCase()}` : ''; }, [studentId]);
  async function start(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { await request('/api/auth/register/start', { method: 'POST', body: JSON.stringify({ name, studentId, requestedDepartmentId: departmentId || null }) }); setStatus('PENDING'); setMessage('提交成功，等待总书记审核。'); } catch (error) { setMessage(error instanceof Error ? error.message : '申请失败。'); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#FAFAF8] flex items-center justify-center p-5"><section className="w-full max-w-lg rounded-2xl border border-border bg-white p-6 sm:p-9 shadow-sm"><h1 className="text-2xl font-semibold">申请加入工作台</h1><p className="mt-2 text-sm text-muted-foreground">提交姓名、学号和申请部门后，须经总书记审核通过才会开通账号。</p>{status === 'FORM' && <form onSubmit={start} className="mt-7 space-y-4"><label className="block text-sm font-medium">姓名<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><label className="block text-sm font-medium">学号<input required value={studentId} onChange={(e) => setStudentId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3" /></label><p className="rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">账号将使用学号：{email || '由系统按学号生成'}</p><label className="block text-sm font-medium">申请部门<select required value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} className="mt-2 h-11 w-full rounded-lg border px-3"><option value="">请选择部门</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><button disabled={busy || !name.trim() || !studentId.trim() || !departmentId} className="h-11 w-full rounded-lg bg-black text-white disabled:bg-black disabled:text-white">{busy ? '提交中…' : '提交申请'}</button></form>}{status === 'PENDING' && <div className="mt-7 rounded-lg bg-muted p-4 text-sm leading-6"><p className="font-medium text-foreground">提交成功，等待总书记审核。</p><p className="mt-1 text-muted-foreground">审核通过后，账号会以管理员配置的初始密码开通；首次登录时必须修改密码。</p></div>}{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}<p className="mt-7 text-center text-sm text-muted-foreground">已有账号？<Link href="/login" className="underline">登录</Link></p></section></main>;
}
